### ISSUE TITLE
Please support promises with rpc calls

### ISSUE THREAD

**Issue by ethanfrey** [mappum/js-tendermint#5]
Trying the following code:

```
let Tendermint = require('tendermint')
const NODE_URI = 'ws://localhost:46657'
let client = Tendermint(NODE_URI)

client.status((err, res) => {console.log(res)})
client.status().then(res => {console.log(res)})
```
The first form with callback returns the proper results.
The second form (promise) returns this:

```
events.js:341
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at Client.once (events.js:341:11)
    at Client.callWs (/home/ethan/js/node_modules/tendermint/lib/client.js:106:14)
    at Client.(anonymous function) [as status] (/home/ethan/js/node_modules/tendermint/lib/client.js:131:19)
    at Object.<anonymous> (/home/ethan/js/test.js:5:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

And I didn't try with `await` syntax yet...

**Comment by mappum** [comment]
I forgot that I had already switched over to Promises in v3, we just have v2 installing as latest by default right now.
